//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdminResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AdminResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user is available with entered password or you have no privilege to access this page..
        /// </summary>
        internal static string AdminCheckFailed {
            get {
                return ResourceManager.GetString("AdminCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promocode is invalid. Please check it once..
        /// </summary>
        internal static string InvalidPromoode {
            get {
                return ResourceManager.GetString("InvalidPromoode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice has been sent succesfully.
        /// </summary>
        internal static string InvoiceSent {
            get {
                return ResourceManager.GetString("InvoiceSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected listing has been deleted successfully..
        /// </summary>
        internal static string ListingDeleteSuccess {
            get {
                return ResourceManager.GetString("ListingDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next action date and time should be eaqual or later than current date time..
        /// </summary>
        internal static string NextActionDateTime {
            get {
                return ResourceManager.GetString("NextActionDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deleted sccessfully..
        /// </summary>
        internal static string SaleCodeDeleteSuccess {
            get {
                return ResourceManager.GetString("SaleCodeDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details Submitted succesfully.
        /// </summary>
        internal static string SalesDetails {
            get {
                return ResourceManager.GetString("SalesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Sales People Access.
        /// </summary>
        internal static string SalesPeople {
            get {
                return ResourceManager.GetString("SalesPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales person created succesfully.
        /// </summary>
        internal static string SalesPersonCreated {
            get {
                return ResourceManager.GetString("SalesPersonCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management Access.
        /// </summary>
        internal static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version has been updated for selected member..
        /// </summary>
        internal static string VerionUpdateSuccess {
            get {
                return ResourceManager.GetString("VerionUpdateSuccess", resourceCulture);
            }
        }
    }
}
