INSERT INTO L_CustomModuleAppIcons(ModuleID,AppIcon,DomainName,IsPrivate)
VALUES(1,'Accounting','twoviecom',0),
(1,'Accounting_Private','twoviecom',1),
(1,'Car','twoviecom',0),
(1,'Car_Private','twoviecom',1),
(1,'Carpenter','twoviecom',0),
(1,'Carpenter_Private','twoviecom',1),
(1,'Cat','twoviecom',0),
(1,'Cat_Private','twoviecom',1),
(1,'Chef','twoviecom',0),
(1,'Chef_Private','twoviecom',1),
(1,'ChildCare','twoviecom',0),
(1,'ChildCare_Private','twoviecom',1),
(1,'CoffeeShop','twoviecom',0),
(1,'CoffeeShop_Private','twoviecom',1),
(1,'Construction','twoviecom',0),
(1,'Construction_Private','twoviecom',1),
(1,'Cook','twoviecom',0),
(1,'Cook_Private','twoviecom',1),
(1,'Dog','twoviecom',0),
(1,'Dog_Private','twoviecom',1),
(1,'Gardener','twoviecom',0),
(1,'Gardener_Private','twoviecom',1),
(1,'Gas','twoviecom',0),
(1,'Gas_Private','twoviecom',1),
(1,'GolfCourse','twoviecom',0),
(1,'GolfCourse_Private','twoviecom',1),
(1,'Handyman','twoviecom',0),
(1,'Handyman_Private','twoviecom',1),
(1,'Housekeeping','twoviecom',0),
(1,'Housekeeping_Private','twoviecom',1),
(1,'Lodging','twoviecom',0),
(1,'Lodging_Private','twoviecom',1),
(1,'MailingShipping','twoviecom',0),
(1,'MailingShipping_Private','twoviecom',1),
(1,'Mechanic','twoviecom',0),
(1,'Mechanic_Private','twoviecom',1),
(1,'MedicalAssistance','twoviecom',0),
(1,'MedicalAssistance_Private','twoviecom',1),
(1,'PestControl','twoviecom',0),
(1,'PestControl_Private','twoviecom',1),
(1,'Plumber','twoviecom',0),
(1,'Plumber_Private','twoviecom',1),
(1,'Restaurent','twoviecom',0),
(1,'Restaurent_Private','twoviecom',1),
(1,'Salon','twoviecom',0),
(1,'Salon_Private','twoviecom',1),
(1,'Taxi','twoviecom',0),
(1,'Taxi_Private','twoviecom',1),
(1,'Theater','twoviecom',0),
(1,'Theater_Private','twoviecom',1),
(1,'Trucking','twoviecom',0),
(1,'Trucking_Private','twoviecom',1),
(1,'WildAnimalPaw','twoviecom',0),
(1,'WildAnimalPaw_Private','twoviecom',1),
(1,'Wine','twoviecom',0),
(1,'Wine_Private','twoviecom',1),
(1,'WineBottle','twoviecom',0),
(1,'WineBottle_Private','twoviecom',1)





