//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC.USPDhubClientService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="USPDhubClientService.ClientServiceSoap")]
    public interface ClientServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetUserDetails(string username, string domainName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSuperAdminiDetails1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetSuperAdminiDetails1(out string superAdminUserName, string username, string domainName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBusinessProfileByUserID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetBusinessProfileByUserID(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Getorderidbyuserid", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Getorderidbyuserid(int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserDetailsByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetUserDetailsByID(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserActivationCodeForRegistration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckUserActivationCodeForRegistration(int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProfileIDByUserID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetProfileIDByUserID(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserDetailsByUserID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetUserDetailsByUserID(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMobileAppAlerts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetMobileAppAlerts(bool flag, int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMobileTips", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetMobileTips(bool flag, int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDesktopMobileAlerts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDesktopMobileAlerts(int pUserID, bool pFlag, System.DateTime pPoolDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDesktopMobileAlertsByPoolDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDesktopMobileAlertsByPoolDate(int pUserID, bool pFlag, System.DateTime pPoolDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateStatusForMobileAlerts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable UpdateStatusForMobileAlerts(int userID, int contactID, bool flag, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMobileAppAlertsForDesktop", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetMobileAppAlertsForDesktop(string pSource, int pUserID, int pRowCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConfigSettingByPID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetConfigSettingByPID(string pProfileID, string pType, string pConfigName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConfigSettingsByVertical", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetConfigSettingsByVertical(string pDomain, string pType, string pConfigName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTipsManagerAudioFilePath", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetTipsManagerAudioFilePath(string pProfileID, string pVerticalDomain);
        
        // CODEGEN: Parameter 'audioBytes' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadAudioFiles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        POC.USPDhubClientService.UploadAudioFilesResponse UploadAudioFiles(POC.USPDhubClientService.UploadAudioFilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAudioTipsManager", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAudioTipsManager(int profileId, int userId, string domainName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteAudioTipsManager", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DeleteAudioTipsManager(int audioID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertUpdateAudioTipsManager", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void InsertUpdateAudioTipsManager(int audioID, int ProfileID, int UserID, string audioName, string audioFile, bool isDefault, int DefaultAudioID, string AudioType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PlayAudioTipsManager", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PlayAudioTipsManager(string audioType, int ProfileID, string audioFile, string DomainName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ErrorHandling", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ErrorHandling(string errorType, string pPageName, string methodName, string message, string strackTrace, string innerException, string data, string AppNanme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetModuleTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] GetModuleTypes(string UserID, string DomainName);
        
        // CODEGEN: Parameter 'pExpiryDate' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_DesktopPOC_ModulContent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        POC.USPDhubClientService.Insert_DesktopPOC_ModulContentResponse Insert_DesktopPOC_ModulContent(POC.USPDhubClientService.Insert_DesktopPOC_ModulContentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPOC_ModuleContentHistory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPOC_ModuleContentHistory(int pProfileID);
        
        // CODEGEN: Parameter 'pExpiryDate' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertBulletinDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        POC.USPDhubClientService.InsertBulletinDetailsResponse InsertBulletinDetails(POC.USPDhubClientService.InsertBulletinDetailsRequest request);
        
        // CODEGEN: Parameter 'pPublishDate' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertBusinessUpdateDetailsNew", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        POC.USPDhubClientService.InsertBusinessUpdateDetailsNewResponse InsertBusinessUpdateDetailsNew(POC.USPDhubClientService.InsertBusinessUpdateDetailsNewRequest request);
        
        // CODEGEN: Parameter 'imgBytes' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadPOCImage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        POC.USPDhubClientService.UploadPOCImageResponse UploadPOCImage(POC.USPDhubClientService.UploadPOCImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPermissionsById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPermissionsById(int associateID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAssociateUserDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAssociateUserDetails(string username, string domainName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendAuthorNotifications", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendAuthorNotifications(string C_Username, int ID, string ModuleName, int UserID, string Username, string DomainName, string C_UserID, string RootPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertToUserTimeZone", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.DateTime ConvertToUserTimeZone(int profileID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertUserTimeZoneToPST", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.DateTime ConvertUserTimeZoneToPST(System.DateTime dtuserDate);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadAudioFiles", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadAudioFilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] audioBytes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string audioFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int userID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int profileID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public bool chkDefault;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string domain;
        
        public UploadAudioFilesRequest() {
        }
        
        public UploadAudioFilesRequest(byte[] audioBytes, string fileName, string audioFileName, int userID, int profileID, bool chkDefault, string domain) {
            this.audioBytes = audioBytes;
            this.fileName = fileName;
            this.audioFileName = audioFileName;
            this.userID = userID;
            this.profileID = profileID;
            this.chkDefault = chkDefault;
            this.domain = domain;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadAudioFilesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadAudioFilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Data.DataTable UploadAudioFilesResult;
        
        public UploadAudioFilesResponse() {
        }
        
        public UploadAudioFilesResponse(System.Data.DataTable UploadAudioFilesResult) {
            this.UploadAudioFilesResult = UploadAudioFilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insert_DesktopPOC_ModulContent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Insert_DesktopPOC_ModulContentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pProfileID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pModuleType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string pDomainVertical;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string pTitle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string pPreviewHTML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string pEditHTML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int pCreatedUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int pModifyUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public bool pIsCall;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public bool pIsContactUs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public bool pisPublic;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> pExpiryDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> pPublishDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public bool IsPublish;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=14)]
        public bool pIsDesktopPOC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=15)]
        public int pPublishID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=16)]
        public int pUserID;
        
        public Insert_DesktopPOC_ModulContentRequest() {
        }
        
        public Insert_DesktopPOC_ModulContentRequest(
                    int pProfileID, 
                    string pModuleType, 
                    string pDomainVertical, 
                    string pTitle, 
                    string pPreviewHTML, 
                    string pEditHTML, 
                    int pCreatedUser, 
                    int pModifyUser, 
                    bool pIsCall, 
                    bool pIsContactUs, 
                    bool pisPublic, 
                    System.Nullable<System.DateTime> pExpiryDate, 
                    System.Nullable<System.DateTime> pPublishDate, 
                    bool IsPublish, 
                    bool pIsDesktopPOC, 
                    int pPublishID, 
                    int pUserID) {
            this.pProfileID = pProfileID;
            this.pModuleType = pModuleType;
            this.pDomainVertical = pDomainVertical;
            this.pTitle = pTitle;
            this.pPreviewHTML = pPreviewHTML;
            this.pEditHTML = pEditHTML;
            this.pCreatedUser = pCreatedUser;
            this.pModifyUser = pModifyUser;
            this.pIsCall = pIsCall;
            this.pIsContactUs = pIsContactUs;
            this.pisPublic = pisPublic;
            this.pExpiryDate = pExpiryDate;
            this.pPublishDate = pPublishDate;
            this.IsPublish = IsPublish;
            this.pIsDesktopPOC = pIsDesktopPOC;
            this.pPublishID = pPublishID;
            this.pUserID = pUserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Insert_DesktopPOC_ModulContentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Insert_DesktopPOC_ModulContentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Insert_DesktopPOC_ModulContentResult;
        
        public Insert_DesktopPOC_ModulContentResponse() {
        }
        
        public Insert_DesktopPOC_ModulContentResponse(int Insert_DesktopPOC_ModulContentResult) {
            this.Insert_DesktopPOC_ModulContentResult = Insert_DesktopPOC_ModulContentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertBulletinDetails", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertBulletinDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pBulletinID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pTemplateBID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string pBulletinTitle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string pBulletinHTML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string pBulletinXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int pCreatedUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int pModifyUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public bool pIsArchive;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public int pUserID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public int pProfileID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public bool pIsCall;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public bool pIsPhotoCapture;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public bool pIsContactUs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public bool pIsPrivate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=14)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> pExpiryDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=15)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> pPublishDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=16)]
        public string Category;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=17)]
        public bool IsPublic;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=18)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PublishedBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=19)]
        public string printerHtml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=20)]
        public string pCustomXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=21)]
        public string pListDescription;
        
        public InsertBulletinDetailsRequest() {
        }
        
        public InsertBulletinDetailsRequest(
                    int pBulletinID, 
                    int pTemplateBID, 
                    string pBulletinTitle, 
                    string pBulletinHTML, 
                    string pBulletinXML, 
                    int pCreatedUser, 
                    int pModifyUser, 
                    bool pIsArchive, 
                    int pUserID, 
                    int pProfileID, 
                    bool pIsCall, 
                    bool pIsPhotoCapture, 
                    bool pIsContactUs, 
                    bool pIsPrivate, 
                    System.Nullable<System.DateTime> pExpiryDate, 
                    System.Nullable<System.DateTime> pPublishDate, 
                    string Category, 
                    bool IsPublic, 
                    System.Nullable<int> PublishedBy, 
                    string printerHtml, 
                    string pCustomXML, 
                    string pListDescription) {
            this.pBulletinID = pBulletinID;
            this.pTemplateBID = pTemplateBID;
            this.pBulletinTitle = pBulletinTitle;
            this.pBulletinHTML = pBulletinHTML;
            this.pBulletinXML = pBulletinXML;
            this.pCreatedUser = pCreatedUser;
            this.pModifyUser = pModifyUser;
            this.pIsArchive = pIsArchive;
            this.pUserID = pUserID;
            this.pProfileID = pProfileID;
            this.pIsCall = pIsCall;
            this.pIsPhotoCapture = pIsPhotoCapture;
            this.pIsContactUs = pIsContactUs;
            this.pIsPrivate = pIsPrivate;
            this.pExpiryDate = pExpiryDate;
            this.pPublishDate = pPublishDate;
            this.Category = Category;
            this.IsPublic = IsPublic;
            this.PublishedBy = PublishedBy;
            this.printerHtml = printerHtml;
            this.pCustomXML = pCustomXML;
            this.pListDescription = pListDescription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertBulletinDetailsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertBulletinDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int InsertBulletinDetailsResult;
        
        public InsertBulletinDetailsResponse() {
        }
        
        public InsertBulletinDetailsResponse(int InsertBulletinDetailsResult) {
            this.InsertBulletinDetailsResult = InsertBulletinDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertBusinessUpdateDetailsNew", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertBusinessUpdateDetailsNewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int updateID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int profileID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string title;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public bool status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string businessDesc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string updateName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public bool progressLevel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public bool isPublic;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> pPublishDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public string pEditHtml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> publishedBy;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public string pListDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> pExDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=14)]
        public bool pIsCall;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=15)]
        public bool pIsContactUs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=16)]
        public int pUserID;
        
        public InsertBusinessUpdateDetailsNewRequest() {
        }
        
        public InsertBusinessUpdateDetailsNewRequest(
                    int updateID, 
                    int profileID, 
                    string title, 
                    bool status, 
                    string businessDesc, 
                    string updateName, 
                    bool progressLevel, 
                    bool isPublic, 
                    int id, 
                    System.Nullable<System.DateTime> pPublishDate, 
                    string pEditHtml, 
                    System.Nullable<int> publishedBy, 
                    string pListDescription, 
                    System.Nullable<System.DateTime> pExDate, 
                    bool pIsCall, 
                    bool pIsContactUs, 
                    int pUserID) {
            this.updateID = updateID;
            this.profileID = profileID;
            this.title = title;
            this.status = status;
            this.businessDesc = businessDesc;
            this.updateName = updateName;
            this.progressLevel = progressLevel;
            this.isPublic = isPublic;
            this.id = id;
            this.pPublishDate = pPublishDate;
            this.pEditHtml = pEditHtml;
            this.publishedBy = publishedBy;
            this.pListDescription = pListDescription;
            this.pExDate = pExDate;
            this.pIsCall = pIsCall;
            this.pIsContactUs = pIsContactUs;
            this.pUserID = pUserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertBusinessUpdateDetailsNewResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InsertBusinessUpdateDetailsNewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int InsertBusinessUpdateDetailsNewResult;
        
        public InsertBusinessUpdateDetailsNewResponse() {
        }
        
        public InsertBusinessUpdateDetailsNewResponse(int InsertBusinessUpdateDetailsNewResult) {
            this.InsertBusinessUpdateDetailsNewResult = InsertBusinessUpdateDetailsNewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadPOCImage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadPOCImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] imgBytes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ProfileID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string fileName;
        
        public UploadPOCImageRequest() {
        }
        
        public UploadPOCImageRequest(byte[] imgBytes, string ProfileID, string fileName) {
            this.imgBytes = imgBytes;
            this.ProfileID = ProfileID;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadPOCImageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadPOCImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UploadPOCImageResult;
        
        public UploadPOCImageResponse() {
        }
        
        public UploadPOCImageResponse(bool UploadPOCImageResult) {
            this.UploadPOCImageResult = UploadPOCImageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientServiceSoapChannel : POC.USPDhubClientService.ClientServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientServiceSoapClient : System.ServiceModel.ClientBase<POC.USPDhubClientService.ClientServiceSoap>, POC.USPDhubClientService.ClientServiceSoap {
        
        public ClientServiceSoapClient() {
        }
        
        public ClientServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Data.DataTable GetUserDetails(string username, string domainName) {
            return base.Channel.GetUserDetails(username, domainName);
        }
        
        public System.Data.DataTable GetSuperAdminiDetails1(out string superAdminUserName, string username, string domainName) {
            return base.Channel.GetSuperAdminiDetails1(out superAdminUserName, username, domainName);
        }
        
        public System.Data.DataTable GetBusinessProfileByUserID(int userID) {
            return base.Channel.GetBusinessProfileByUserID(userID);
        }
        
        public System.Data.DataTable Getorderidbyuserid(int userid) {
            return base.Channel.Getorderidbyuserid(userid);
        }
        
        public System.Data.DataTable GetUserDetailsByID(int userID) {
            return base.Channel.GetUserDetailsByID(userID);
        }
        
        public string CheckUserActivationCodeForRegistration(int userid) {
            return base.Channel.CheckUserActivationCodeForRegistration(userid);
        }
        
        public int GetProfileIDByUserID(int userID) {
            return base.Channel.GetProfileIDByUserID(userID);
        }
        
        public System.Data.DataTable GetUserDetailsByUserID(int userID) {
            return base.Channel.GetUserDetailsByUserID(userID);
        }
        
        public System.Data.DataTable GetMobileAppAlerts(bool flag, int userID) {
            return base.Channel.GetMobileAppAlerts(flag, userID);
        }
        
        public System.Data.DataTable GetMobileTips(bool flag, int userID) {
            return base.Channel.GetMobileTips(flag, userID);
        }
        
        public System.Data.DataTable GetDesktopMobileAlerts(int pUserID, bool pFlag, System.DateTime pPoolDate) {
            return base.Channel.GetDesktopMobileAlerts(pUserID, pFlag, pPoolDate);
        }
        
        public System.Data.DataTable GetDesktopMobileAlertsByPoolDate(int pUserID, bool pFlag, System.DateTime pPoolDate) {
            return base.Channel.GetDesktopMobileAlertsByPoolDate(pUserID, pFlag, pPoolDate);
        }
        
        public System.Data.DataTable UpdateStatusForMobileAlerts(int userID, int contactID, bool flag, int id) {
            return base.Channel.UpdateStatusForMobileAlerts(userID, contactID, flag, id);
        }
        
        public System.Data.DataTable GetMobileAppAlertsForDesktop(string pSource, int pUserID, int pRowCount) {
            return base.Channel.GetMobileAppAlertsForDesktop(pSource, pUserID, pRowCount);
        }
        
        public string GetConfigSettingByPID(string pProfileID, string pType, string pConfigName) {
            return base.Channel.GetConfigSettingByPID(pProfileID, pType, pConfigName);
        }
        
        public string GetConfigSettingsByVertical(string pDomain, string pType, string pConfigName) {
            return base.Channel.GetConfigSettingsByVertical(pDomain, pType, pConfigName);
        }
        
        public string GetTipsManagerAudioFilePath(string pProfileID, string pVerticalDomain) {
            return base.Channel.GetTipsManagerAudioFilePath(pProfileID, pVerticalDomain);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POC.USPDhubClientService.UploadAudioFilesResponse POC.USPDhubClientService.ClientServiceSoap.UploadAudioFiles(POC.USPDhubClientService.UploadAudioFilesRequest request) {
            return base.Channel.UploadAudioFiles(request);
        }
        
        public System.Data.DataTable UploadAudioFiles(byte[] audioBytes, string fileName, string audioFileName, int userID, int profileID, bool chkDefault, string domain) {
            POC.USPDhubClientService.UploadAudioFilesRequest inValue = new POC.USPDhubClientService.UploadAudioFilesRequest();
            inValue.audioBytes = audioBytes;
            inValue.fileName = fileName;
            inValue.audioFileName = audioFileName;
            inValue.userID = userID;
            inValue.profileID = profileID;
            inValue.chkDefault = chkDefault;
            inValue.domain = domain;
            POC.USPDhubClientService.UploadAudioFilesResponse retVal = ((POC.USPDhubClientService.ClientServiceSoap)(this)).UploadAudioFiles(inValue);
            return retVal.UploadAudioFilesResult;
        }
        
        public System.Data.DataTable GetAudioTipsManager(int profileId, int userId, string domainName) {
            return base.Channel.GetAudioTipsManager(profileId, userId, domainName);
        }
        
        public void DeleteAudioTipsManager(int audioID) {
            base.Channel.DeleteAudioTipsManager(audioID);
        }
        
        public void InsertUpdateAudioTipsManager(int audioID, int ProfileID, int UserID, string audioName, string audioFile, bool isDefault, int DefaultAudioID, string AudioType) {
            base.Channel.InsertUpdateAudioTipsManager(audioID, ProfileID, UserID, audioName, audioFile, isDefault, DefaultAudioID, AudioType);
        }
        
        public string PlayAudioTipsManager(string audioType, int ProfileID, string audioFile, string DomainName) {
            return base.Channel.PlayAudioTipsManager(audioType, ProfileID, audioFile, DomainName);
        }
        
        public void ErrorHandling(string errorType, string pPageName, string methodName, string message, string strackTrace, string innerException, string data, string AppNanme) {
            base.Channel.ErrorHandling(errorType, pPageName, methodName, message, strackTrace, innerException, data, AppNanme);
        }
        
        public string[] GetModuleTypes(string UserID, string DomainName) {
            return base.Channel.GetModuleTypes(UserID, DomainName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POC.USPDhubClientService.Insert_DesktopPOC_ModulContentResponse POC.USPDhubClientService.ClientServiceSoap.Insert_DesktopPOC_ModulContent(POC.USPDhubClientService.Insert_DesktopPOC_ModulContentRequest request) {
            return base.Channel.Insert_DesktopPOC_ModulContent(request);
        }
        
        public int Insert_DesktopPOC_ModulContent(
                    int pProfileID, 
                    string pModuleType, 
                    string pDomainVertical, 
                    string pTitle, 
                    string pPreviewHTML, 
                    string pEditHTML, 
                    int pCreatedUser, 
                    int pModifyUser, 
                    bool pIsCall, 
                    bool pIsContactUs, 
                    bool pisPublic, 
                    System.Nullable<System.DateTime> pExpiryDate, 
                    System.Nullable<System.DateTime> pPublishDate, 
                    bool IsPublish, 
                    bool pIsDesktopPOC, 
                    int pPublishID, 
                    int pUserID) {
            POC.USPDhubClientService.Insert_DesktopPOC_ModulContentRequest inValue = new POC.USPDhubClientService.Insert_DesktopPOC_ModulContentRequest();
            inValue.pProfileID = pProfileID;
            inValue.pModuleType = pModuleType;
            inValue.pDomainVertical = pDomainVertical;
            inValue.pTitle = pTitle;
            inValue.pPreviewHTML = pPreviewHTML;
            inValue.pEditHTML = pEditHTML;
            inValue.pCreatedUser = pCreatedUser;
            inValue.pModifyUser = pModifyUser;
            inValue.pIsCall = pIsCall;
            inValue.pIsContactUs = pIsContactUs;
            inValue.pisPublic = pisPublic;
            inValue.pExpiryDate = pExpiryDate;
            inValue.pPublishDate = pPublishDate;
            inValue.IsPublish = IsPublish;
            inValue.pIsDesktopPOC = pIsDesktopPOC;
            inValue.pPublishID = pPublishID;
            inValue.pUserID = pUserID;
            POC.USPDhubClientService.Insert_DesktopPOC_ModulContentResponse retVal = ((POC.USPDhubClientService.ClientServiceSoap)(this)).Insert_DesktopPOC_ModulContent(inValue);
            return retVal.Insert_DesktopPOC_ModulContentResult;
        }
        
        public System.Data.DataTable GetPOC_ModuleContentHistory(int pProfileID) {
            return base.Channel.GetPOC_ModuleContentHistory(pProfileID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POC.USPDhubClientService.InsertBulletinDetailsResponse POC.USPDhubClientService.ClientServiceSoap.InsertBulletinDetails(POC.USPDhubClientService.InsertBulletinDetailsRequest request) {
            return base.Channel.InsertBulletinDetails(request);
        }
        
        public int InsertBulletinDetails(
                    int pBulletinID, 
                    int pTemplateBID, 
                    string pBulletinTitle, 
                    string pBulletinHTML, 
                    string pBulletinXML, 
                    int pCreatedUser, 
                    int pModifyUser, 
                    bool pIsArchive, 
                    int pUserID, 
                    int pProfileID, 
                    bool pIsCall, 
                    bool pIsPhotoCapture, 
                    bool pIsContactUs, 
                    bool pIsPrivate, 
                    System.Nullable<System.DateTime> pExpiryDate, 
                    System.Nullable<System.DateTime> pPublishDate, 
                    string Category, 
                    bool IsPublic, 
                    System.Nullable<int> PublishedBy, 
                    string printerHtml, 
                    string pCustomXML, 
                    string pListDescription) {
            POC.USPDhubClientService.InsertBulletinDetailsRequest inValue = new POC.USPDhubClientService.InsertBulletinDetailsRequest();
            inValue.pBulletinID = pBulletinID;
            inValue.pTemplateBID = pTemplateBID;
            inValue.pBulletinTitle = pBulletinTitle;
            inValue.pBulletinHTML = pBulletinHTML;
            inValue.pBulletinXML = pBulletinXML;
            inValue.pCreatedUser = pCreatedUser;
            inValue.pModifyUser = pModifyUser;
            inValue.pIsArchive = pIsArchive;
            inValue.pUserID = pUserID;
            inValue.pProfileID = pProfileID;
            inValue.pIsCall = pIsCall;
            inValue.pIsPhotoCapture = pIsPhotoCapture;
            inValue.pIsContactUs = pIsContactUs;
            inValue.pIsPrivate = pIsPrivate;
            inValue.pExpiryDate = pExpiryDate;
            inValue.pPublishDate = pPublishDate;
            inValue.Category = Category;
            inValue.IsPublic = IsPublic;
            inValue.PublishedBy = PublishedBy;
            inValue.printerHtml = printerHtml;
            inValue.pCustomXML = pCustomXML;
            inValue.pListDescription = pListDescription;
            POC.USPDhubClientService.InsertBulletinDetailsResponse retVal = ((POC.USPDhubClientService.ClientServiceSoap)(this)).InsertBulletinDetails(inValue);
            return retVal.InsertBulletinDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POC.USPDhubClientService.InsertBusinessUpdateDetailsNewResponse POC.USPDhubClientService.ClientServiceSoap.InsertBusinessUpdateDetailsNew(POC.USPDhubClientService.InsertBusinessUpdateDetailsNewRequest request) {
            return base.Channel.InsertBusinessUpdateDetailsNew(request);
        }
        
        public int InsertBusinessUpdateDetailsNew(
                    int updateID, 
                    int profileID, 
                    string title, 
                    bool status, 
                    string businessDesc, 
                    string updateName, 
                    bool progressLevel, 
                    bool isPublic, 
                    int id, 
                    System.Nullable<System.DateTime> pPublishDate, 
                    string pEditHtml, 
                    System.Nullable<int> publishedBy, 
                    string pListDescription, 
                    System.Nullable<System.DateTime> pExDate, 
                    bool pIsCall, 
                    bool pIsContactUs, 
                    int pUserID) {
            POC.USPDhubClientService.InsertBusinessUpdateDetailsNewRequest inValue = new POC.USPDhubClientService.InsertBusinessUpdateDetailsNewRequest();
            inValue.updateID = updateID;
            inValue.profileID = profileID;
            inValue.title = title;
            inValue.status = status;
            inValue.businessDesc = businessDesc;
            inValue.updateName = updateName;
            inValue.progressLevel = progressLevel;
            inValue.isPublic = isPublic;
            inValue.id = id;
            inValue.pPublishDate = pPublishDate;
            inValue.pEditHtml = pEditHtml;
            inValue.publishedBy = publishedBy;
            inValue.pListDescription = pListDescription;
            inValue.pExDate = pExDate;
            inValue.pIsCall = pIsCall;
            inValue.pIsContactUs = pIsContactUs;
            inValue.pUserID = pUserID;
            POC.USPDhubClientService.InsertBusinessUpdateDetailsNewResponse retVal = ((POC.USPDhubClientService.ClientServiceSoap)(this)).InsertBusinessUpdateDetailsNew(inValue);
            return retVal.InsertBusinessUpdateDetailsNewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POC.USPDhubClientService.UploadPOCImageResponse POC.USPDhubClientService.ClientServiceSoap.UploadPOCImage(POC.USPDhubClientService.UploadPOCImageRequest request) {
            return base.Channel.UploadPOCImage(request);
        }
        
        public bool UploadPOCImage(byte[] imgBytes, string ProfileID, string fileName) {
            POC.USPDhubClientService.UploadPOCImageRequest inValue = new POC.USPDhubClientService.UploadPOCImageRequest();
            inValue.imgBytes = imgBytes;
            inValue.ProfileID = ProfileID;
            inValue.fileName = fileName;
            POC.USPDhubClientService.UploadPOCImageResponse retVal = ((POC.USPDhubClientService.ClientServiceSoap)(this)).UploadPOCImage(inValue);
            return retVal.UploadPOCImageResult;
        }
        
        public System.Data.DataTable GetPermissionsById(int associateID) {
            return base.Channel.GetPermissionsById(associateID);
        }
        
        public System.Data.DataTable GetAssociateUserDetails(string username, string domainName) {
            return base.Channel.GetAssociateUserDetails(username, domainName);
        }
        
        public string SendAuthorNotifications(string C_Username, int ID, string ModuleName, int UserID, string Username, string DomainName, string C_UserID, string RootPath) {
            return base.Channel.SendAuthorNotifications(C_Username, ID, ModuleName, UserID, Username, DomainName, C_UserID, RootPath);
        }
        
        public System.DateTime ConvertToUserTimeZone(int profileID) {
            return base.Channel.ConvertToUserTimeZone(profileID);
        }
        
        public System.DateTime ConvertUserTimeZoneToPST(System.DateTime dtuserDate) {
            return base.Channel.ConvertUserTimeZoneToPST(dtuserDate);
        }
    }
}
