//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36366
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LabelMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LabelMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LabelMessages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your groups were successfully added..
        /// </summary>
        internal static string AddContactGroupList {
            get {
                return ResourceManager.GetString("AddContactGroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have exceeded the maximum limit of groups..
        /// </summary>
        internal static string AddContactGroupListcountExceeded {
            get {
                return ResourceManager.GetString("AddContactGroupListcountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contacts were successfully added..
        /// </summary>
        internal static string AddcontactinAddcontact {
            get {
                return ResourceManager.GetString("AddcontactinAddcontact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected forms have been added  successfully to your favorites list..
        /// </summary>
        internal static string AddFavoriteSuccess {
            get {
                return ResourceManager.GetString("AddFavoriteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry, there is a temporary problem with our e-mail service. Please try after some time..
        /// </summary>
        internal static string Affiliateinvitationfailmessage {
            get {
                return ResourceManager.GetString("Affiliateinvitationfailmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your invitation(s) have been sent successfully..
        /// </summary>
        internal static string Affiliateinvitationsendmessage {
            get {
                return ResourceManager.GetString("Affiliateinvitationsendmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you cannot send bulletin now as you have bulletin campaign scheduled till.
        /// </summary>
        internal static string AlreadyHaveBulletinCampaign {
            get {
                return ResourceManager.GetString("AlreadyHaveBulletinCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you cannot send event now as you have event campaign scheduled till.
        /// </summary>
        internal static string AlreadyHaveBusinessEventCampaign {
            get {
                return ResourceManager.GetString("AlreadyHaveBusinessEventCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you cannot send update now as you have update campaign scheduled till.
        /// </summary>
        internal static string AlreadyHaveBusinessUpdateCampaign {
            get {
                return ResourceManager.GetString("AlreadyHaveBusinessUpdateCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you cannot market your coupon now as you have a coupon campaign scheduled till.
        /// </summary>
        internal static string AlreadyHaveCouponCampan {
            get {
                return ResourceManager.GetString("AlreadyHaveCouponCampan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot send another email campaign until the current campaign has ended. Your current email campaign is scheduled until.
        /// </summary>
        internal static string AlreadyHaveEmailCampan {
            get {
                return ResourceManager.GetString("AlreadyHaveEmailCampan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you are not able to send another campaign now as you already have 3 campaigns scheduled till.
        /// </summary>
        internal static string AlreadyHaveNewsletterCampan {
            get {
                return ResourceManager.GetString("AlreadyHaveNewsletterCampan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already sent an invitation to ##Email##..
        /// </summary>
        internal static string AlreadySent {
            get {
                return ResourceManager.GetString("AlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your #type# has been reinstated successfully..
        /// </summary>
        internal static string ArchiveCurrentSuccess {
            get {
                return ResourceManager.GetString("ArchiveCurrentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you cannot archive your flyer now as you have an flyer campaign scheduled..
        /// </summary>
        internal static string ArchiveSchedulenewsletter {
            get {
                return ResourceManager.GetString("ArchiveSchedulenewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your #type# has been archived successfully..
        /// </summary>
        internal static string ArchiveSuccess {
            get {
                return ResourceManager.GetString("ArchiveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a text to find associates..
        /// </summary>
        internal static string AssociateEmptySearch {
            get {
                return ResourceManager.GetString("AssociateEmptySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit for approval.
        /// </summary>
        internal static string AuthorPublishTitle {
            get {
                return ResourceManager.GetString("AuthorPublishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected banner ad has been deleted successfully..
        /// </summary>
        internal static string BannerAdDeleteSuccess {
            get {
                return ResourceManager.GetString("BannerAdDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Banner Ad Link.
        /// </summary>
        internal static string BannerAdLinkEdit {
            get {
                return ResourceManager.GetString("BannerAdLinkEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link has been updated for banner ad..
        /// </summary>
        internal static string BannerAdLinkSaved {
            get {
                return ResourceManager.GetString("BannerAdLinkSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Display status has been updated for banner ads..
        /// </summary>
        internal static string BannerAdsAppdisplaySuccess {
            get {
                return ResourceManager.GetString("BannerAdsAppdisplaySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your image has been updated successfully..
        /// </summary>
        internal static string BGImageSubmitted {
            get {
                return ResourceManager.GetString("BGImageSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected sender(s) have been blocked successfully..
        /// </summary>
        internal static string BlockedAllSenders {
            get {
                return ResourceManager.GetString("BlockedAllSenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the selected sender(s), few of them have been blocked successfully. &lt;br/&gt; For remaining message(s) do not exists the device id..
        /// </summary>
        internal static string BlockedPartialSenders {
            get {
                return ResourceManager.GetString("BlockedPartialSenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocking is unavailable for the selected sender(s)..
        /// </summary>
        internal static string BlockedSendersFailed {
            get {
                return ResourceManager.GetString("BlockedSendersFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sender have been blocked successfully.
        /// </summary>
        internal static string BlockSender {
            get {
                return ResourceManager.GetString("BlockSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #BulletinName# has been created successfully..
        /// </summary>
        internal static string BulletingCreateSuccess {
            get {
                return ResourceManager.GetString("BulletingCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #BulletinName# has been updated successfully..
        /// </summary>
        internal static string BulletingUpdateSuccess {
            get {
                return ResourceManager.GetString("BulletingUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to organization name.
        /// </summary>
        internal static string BusinessName {
            get {
                return ResourceManager.GetString("BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change the visiblity..
        /// </summary>
        internal static string CallAddOnVisibilityFailed {
            get {
                return ResourceManager.GetString("CallAddOnVisibilityFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Button has been changed to Off..
        /// </summary>
        internal static string CallAddOnVisibilityOff {
            get {
                return ResourceManager.GetString("CallAddOnVisibilityOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Button is now On..
        /// </summary>
        internal static string CallAddOnVisibilityOn {
            get {
                return ResourceManager.GetString("CallAddOnVisibilityOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have no group names. Please add group name and try again..!.
        /// </summary>
        internal static string checkforlistingvalues {
            get {
                return ResourceManager.GetString("checkforlistingvalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment process has been completed..
        /// </summary>
        internal static string CheckOutSuccess {
            get {
                return ResourceManager.GetString("CheckOutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        internal static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your coupon campaign has been cancelled successfully..
        /// </summary>
        internal static string CoponCampaignstoped {
            get {
                return ResourceManager.GetString("CoponCampaignstoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your coupon campaign  has been scheduled successfully..
        /// </summary>
        internal static string CouponScheduledSuccessfully {
            get {
                return ResourceManager.GetString("CouponScheduledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your custom module expired, please renew again to use it..
        /// </summary>
        internal static string CustomModuleExpired {
            get {
                return ResourceManager.GetString("CustomModuleExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date of birth should be equal or less than current date..
        /// </summary>
        internal static string DateofBirth {
            get {
                return ResourceManager.GetString("DateofBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this contact? .
        /// </summary>
        internal static string Deletecontactinshowcontact {
            get {
                return ResourceManager.GetString("Deletecontactinshowcontact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected items have been deleted successfully..
        /// </summary>
        internal static string DeleteMessagesandTips {
            get {
                return ResourceManager.GetString("DeleteMessagesandTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you cannot delete your coupon now as you have a coupon campaign scheduled till.
        /// </summary>
        internal static string DeleteScheduleCoupon {
            get {
                return ResourceManager.GetString("DeleteScheduleCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you cannot delete your email now as you have an email campaign scheduled till.
        /// </summary>
        internal static string DeleteScheduleEmail {
            get {
                return ResourceManager.GetString("DeleteScheduleEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you cannot delete your event now as you have a event campaign scheduled till.
        /// </summary>
        internal static string DeleteScheduleEvent {
            get {
                return ResourceManager.GetString("DeleteScheduleEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you cannot delete your flyer now as you have a flyer campaign scheduled till.
        /// </summary>
        internal static string DeleteSchedulenewsletter {
            get {
                return ResourceManager.GetString("DeleteSchedulenewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your selection(s) have been deleted successfully..
        /// </summary>
        internal static string DeleteSmartConnectMessages {
            get {
                return ResourceManager.GetString("DeleteSmartConnectMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This contact is already present in the selected group. Please choose another group in which to add this contact..
        /// </summary>
        internal static string Duplicatecontactmessage {
            get {
                return ResourceManager.GetString("Duplicatecontactmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number  is already in use; please use a different one..
        /// </summary>
        internal static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of your contacts could not be invited as they have received an Affiliate invitation from you in the past..
        /// </summary>
        internal static string DuplicateInvitations {
            get {
                return ResourceManager.GetString("DuplicateInvitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate group name. Please choose a different name and try again..
        /// </summary>
        internal static string DuplicateListingmessage {
            get {
                return ResourceManager.GetString("DuplicateListingmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button name already exists. Please use another one..
        /// </summary>
        internal static string DuplicateQRTitle {
            get {
                return ResourceManager.GetString("DuplicateQRTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you cannot edit your coupon now because it has already been scheduled..
        /// </summary>
        internal static string EditScheduleCoupon {
            get {
                return ResourceManager.GetString("EditScheduleCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email address.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email campaign has been cancelled successfully..
        /// </summary>
        internal static string EmailCampaignstoped {
            get {
                return ResourceManager.GetString("EmailCampaignstoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, #Available emails are  available to you. You have selected #Selected emails. Please select less than or equal to #Available email(s)..
        /// </summary>
        internal static string EMailsCountExceeded {
            get {
                return ResourceManager.GetString("EMailsCountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date should be later than current date..
        /// </summary>
        internal static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file to upload..
        /// </summary>
        internal static string FileNotSelected {
            get {
                return ResourceManager.GetString("FileNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you cannot send the invite to yourself..
        /// </summary>
        internal static string GeneralTabtosameprofile {
            get {
                return ResourceManager.GetString("GeneralTabtosameprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your invitation(s) were sent successfully..
        /// </summary>
        internal static string Generealtabsendmessage {
            get {
                return ResourceManager.GetString("Generealtabsendmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google events have been imported successfully..
        /// </summary>
        internal static string GoogleEventsImportSuccess {
            get {
                return ResourceManager.GetString("GoogleEventsImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no google events to import..
        /// </summary>
        internal static string GoogleEventsNotExists {
            get {
                return ResourceManager.GetString("GoogleEventsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your image height should be higher than width.Your image specification is #Width#x#Height#.
        /// </summary>
        internal static string ImageHeightLessthanWidth {
            get {
                return ResourceManager.GetString("ImageHeightLessthanWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your image height should be between #MinHeight#px and #MaxHeight#px for the #Width#px of width. Your Image Specification: #Width#x#Height#.
        /// </summary>
        internal static string ImageHeightNotReached {
            get {
                return ResourceManager.GetString("ImageHeightNotReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your uploaded image should be minimum of  #DefinedWidth#px width and #DefinedHeight#px height..
        /// </summary>
        internal static string ImageSizeNotReached {
            get {
                return ResourceManager.GetString("ImageSizeNotReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contacts(#successcount#) were successfully imported..
        /// </summary>
        internal static string ImportContactsSuccess {
            get {
                return ResourceManager.GetString("ImportContactsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has already been activated..
        /// </summary>
        internal static string InvitationActivated {
            get {
                return ResourceManager.GetString("InvitationActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your invitation has been cancelled successfully..
        /// </summary>
        internal static string InvitationCancelled {
            get {
                return ResourceManager.GetString("InvitationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a title..
        /// </summary>
        internal static string ItemTitleEmpty {
            get {
                return ResourceManager.GetString("ItemTitleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last contact date should be equal or less than current date..
        /// </summary>
        internal static string LastContactCurrentDate {
            get {
                return ResourceManager.GetString("LastContactCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last contact date should be equal or later than date of birth..
        /// </summary>
        internal static string LastContactDate {
            get {
                return ResourceManager.GetString("LastContactDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen date should be equal or less than current date..
        /// </summary>
        internal static string LastSeenDate {
            get {
                return ResourceManager.GetString("LastSeenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Last Synced On: &lt;/b&gt;.
        /// </summary>
        internal static string LastSyncDate {
            get {
                return ResourceManager.GetString("LastSyncDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your long logo must be a minimum of.
        /// </summary>
        internal static string LonglogoUploadMessage {
            get {
                return ResourceManager.GetString("LonglogoUploadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year should be less than or equal to current year..
        /// </summary>
        internal static string Manufacturedyear {
            get {
                return ResourceManager.GetString("Manufacturedyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected mobile app message has been deleted successfully..
        /// </summary>
        internal static string MobileMessage {
            get {
                return ResourceManager.GetString("MobileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected mobile app tip has been deleted successfully..
        /// </summary>
        internal static string MobileTip {
            get {
                return ResourceManager.GetString("MobileTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a network problem in your location. Please check it..
        /// </summary>
        internal static string NetworkErrors {
            get {
                return ResourceManager.GetString("NetworkErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your campaign has been cancelled successfully..
        /// </summary>
        internal static string newsletterCampaignstoped {
            get {
                return ResourceManager.GetString("newsletterCampaignstoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently you have no forms are available to add to your favorites list..
        /// </summary>
        internal static string NoAddFavoritesAvailable {
            get {
                return ResourceManager.GetString("NoAddFavoritesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No opens between #StartDate# and #EndDate#..
        /// </summary>
        internal static string NoAppOpenUsageResult {
            get {
                return ResourceManager.GetString("NoAppOpenUsageResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No clicks between #StartDate# and #EndDate#..
        /// </summary>
        internal static string NoClickUsageResult {
            get {
                return ResourceManager.GetString("NoClickUsageResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select or add at least one contact and try again..
        /// </summary>
        internal static string NoContactsSelected {
            get {
                return ResourceManager.GetString("NoContactsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry, you cannot schedule this coupon today. Please try tomorrow..
        /// </summary>
        internal static string NoCountforScheduledcoupon {
            get {
                return ResourceManager.GetString("NoCountforScheduledcoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification has been sent..
        /// </summary>
        internal static string NoDevicesAdded {
            get {
                return ResourceManager.GetString("NoDevicesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a group name..
        /// </summary>
        internal static string NoListEnterederrormessage {
            get {
                return ResourceManager.GetString("NoListEnterederrormessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have any Private QR Connect Messages..
        /// </summary>
        internal static string NoPrivateSmartConnectMessages {
            get {
                return ResourceManager.GetString("NoPrivateSmartConnectMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently you have no forms are available to remove from your favorites list..
        /// </summary>
        internal static string NoRemoveFavoritesAvailable {
            get {
                return ResourceManager.GetString("NoRemoveFavoritesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have SmartConnect Messages..
        /// </summary>
        internal static string NoSmartConnectMessages {
            get {
                return ResourceManager.GetString("NoSmartConnectMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No video available for &apos;##SearchHelpVideo##&apos;..
        /// </summary>
        internal static string NotFoundSearchHelpVideo {
            get {
                return ResourceManager.GetString("NotFoundSearchHelpVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No installs between #StartDate# and #EndDate#..
        /// </summary>
        internal static string NoUsageResult {
            get {
                return ResourceManager.GetString("NoUsageResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order can only be changed for published content.Make sure you have published content and try again..
        /// </summary>
        internal static string OrderChangedPublishedContent {
            get {
                return ResourceManager.GetString("OrderChangedPublishedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have received your information and a customer service representative will be calling you to complete the verification process and account setup or feel free to call us at:  1-800-281-0263.
        /// </summary>
        internal static string OrderCompletedMessage {
            get {
                return ResourceManager.GetString("OrderCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your parent organization doesn&apos;t exists..
        /// </summary>
        internal static string ParentProfileNotExists {
            get {
                return ResourceManager.GetString("ParentProfileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been updated successfully..
        /// </summary>
        internal static string Passwordupdated {
            get {
                return ResourceManager.GetString("Passwordupdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the changes to take effect you will need to logout and then log back in. &lt;a class=&quot;operatelogins&quot; href=&quot;##logoutlink##&quot;&gt;Click here&lt;/a&gt; to logout..
        /// </summary>
        internal static string PermissionSignOut {
            get {
                return ResourceManager.GetString("PermissionSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected private call history has been deleted successfully..
        /// </summary>
        internal static string PrivateCallHistoryDeleteMsg {
            get {
                return ResourceManager.GetString("PrivateCallHistoryDeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your invitation has been deleted succesfully..
        /// </summary>
        internal static string PrivateInvitationDelete {
            get {
                return ResourceManager.GetString("PrivateInvitationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected contacts have been deleted successfully..
        /// </summary>
        internal static string PrivateinvitationDeleteMSG {
            get {
                return ResourceManager.GetString("PrivateinvitationDeleteMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device has been disabled successfully..
        /// </summary>
        internal static string PrivateInvitationDeviceDisable {
            get {
                return ResourceManager.GetString("PrivateInvitationDeviceDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device has been enabled successfully..
        /// </summary>
        internal static string PrivateInvitationDeviceEnable {
            get {
                return ResourceManager.GetString("PrivateInvitationDeviceEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected contacts have been disabled successfully..
        /// </summary>
        internal static string PrivateInvitationDisableMSG {
            get {
                return ResourceManager.GetString("PrivateInvitationDisableMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected contacts have been enabled successfully..
        /// </summary>
        internal static string PrivateInvitationEnableMSG {
            get {
                return ResourceManager.GetString("PrivateInvitationEnableMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your invitation has expired. Please request another invitation from the App owner..
        /// </summary>
        internal static string PrivateInvitationExpiration {
            get {
                return ResourceManager.GetString("PrivateInvitationExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a contact to send an invitation..
        /// </summary>
        internal static string PrivateInvitationPleaseSelectatleastMSG {
            get {
                return ResourceManager.GetString("PrivateInvitationPleaseSelectatleastMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your invitation(s) have been sent successfully..
        /// </summary>
        internal static string PrivateInvitationSentMSG {
            get {
                return ResourceManager.GetString("PrivateInvitationSentMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your invitation have been successfully cancelled..
        /// </summary>
        internal static string PrivateModuleDeclinedTitle {
            get {
                return ResourceManager.GetString("PrivateModuleDeclinedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private QR Connect button copied successfully.
        /// </summary>
        internal static string PrivateSmartConnectCopied {
            get {
                return ResourceManager.GetString("PrivateSmartConnectCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private QR Connect button created successfully.
        /// </summary>
        internal static string PrivateSmartConnectCreated {
            get {
                return ResourceManager.GetString("PrivateSmartConnectCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private QR Connect buttom deleted succesfully.
        /// </summary>
        internal static string PrivateSmartConnectDeleted {
            get {
                return ResourceManager.GetString("PrivateSmartConnectDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to manage Private QR Connect messages..
        /// </summary>
        internal static string PrivateSmartConnectPermission {
            get {
                return ResourceManager.GetString("PrivateSmartConnectPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private QR Connect button updated successfully.
        /// </summary>
        internal static string PrivateSmartConnectUpdated {
            get {
                return ResourceManager.GetString("PrivateSmartConnectUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image is not available.
        /// </summary>
        internal static string PSCNoImage {
            get {
                return ResourceManager.GetString("PSCNoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected button has been changed to off..
        /// </summary>
        internal static string PublicCallAddOnVisibilityOff {
            get {
                return ResourceManager.GetString("PublicCallAddOnVisibilityOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected button is now on..
        /// </summary>
        internal static string PublicCallAddOnVisibilityOn {
            get {
                return ResourceManager.GetString("PublicCallAddOnVisibilityOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected public call history has been deleted successfully..
        /// </summary>
        internal static string PublicCallHistoryDeleteMsg {
            get {
                return ResourceManager.GetString("PublicCallHistoryDeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your #Type# has been changed to #Status# successfully..
        /// </summary>
        internal static string PublishChange {
            get {
                return ResourceManager.GetString("PublishChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish date should be equal or later than current date..
        /// </summary>
        internal static string PublishDateAlert {
            get {
                return ResourceManager.GetString("PublishDateAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your #Type# has been #Status# successfully..
        /// </summary>
        internal static string PublishStatusChange {
            get {
                return ResourceManager.GetString("PublishStatusChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Address.
        /// </summary>
        internal static string QRInvalidAddress {
            get {
                return ResourceManager.GetString("QRInvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your referral has been sent successfully..
        /// </summary>
        internal static string Referafriendmailsentsuccessfully {
            get {
                return ResourceManager.GetString("Referafriendmailsentsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected forms have been removed successfully from your favorites list..
        /// </summary>
        internal static string RemoveFavoriteSuccess {
            get {
                return ResourceManager.GetString("RemoveFavoriteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;#ExistingContentName#&apos; has successfully been renamed to &apos;#NewContentName#&apos;..
        /// </summary>
        internal static string RenameSuccess {
            get {
                return ResourceManager.GetString("RenameSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your membership will be renewed on #RenewalDate#..
        /// </summary>
        internal static string RenewalAlert {
            get {
                return ResourceManager.GetString("RenewalAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your subscription is set to expire on #RenewalDate#. Please ensure your payment has been sent..
        /// </summary>
        internal static string RenewalAlertCheckProcess {
            get {
                return ResourceManager.GetString("RenewalAlertCheckProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report will be available once survey participation begins..
        /// </summary>
        internal static string ReportError {
            get {
                return ResourceManager.GetString("ReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your invitation has been resent successfully..
        /// </summary>
        internal static string ResendSuccess {
            get {
                return ResourceManager.GetString("ResendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your event campaign has been scheduled successfully..
        /// </summary>
        internal static string ScheduleBusinessEvent {
            get {
                return ResourceManager.GetString("ScheduleBusinessEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your update campaign has been scheduled successfully..
        /// </summary>
        internal static string ScheduleBusinessUpdate {
            get {
                return ResourceManager.GetString("ScheduleBusinessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have exceeded the maximum limit for today..
        /// </summary>
        internal static string ScheduledCouponCountExceededforselecteddate {
            get {
                return ResourceManager.GetString("ScheduledCouponCountExceededforselecteddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email campaign has been scheduled successfully..
        /// </summary>
        internal static string ScheduleEmail {
            get {
                return ResourceManager.GetString("ScheduleEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your campaign has been scheduled successfully..
        /// </summary>
        internal static string Schedulenewsletter {
            get {
                return ResourceManager.GetString("Schedulenewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your notification has been sent successfully..
        /// </summary>
        internal static string SchedulePushNotification {
            get {
                return ResourceManager.GetString("SchedulePushNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry, the day limit for sending event emails is #day_lmit, you had already sent #used event emails. From the available options, please choose a value 
        ///
        ///less than or equal to #available.
        ///
        ///.
        /// </summary>
        internal static string SelectedbusinesseventlimitExceedstheAvailablevalue {
            get {
                return ResourceManager.GetString("SelectedbusinesseventlimitExceedstheAvailablevalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your selected event limit value is less than or equal to the available limit value.Please schedule your event.
        /// </summary>
        internal static string SelectedBusinessEventlimitlessthanAvailablevalue {
            get {
                return ResourceManager.GetString("SelectedBusinessEventlimitlessthanAvailablevalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry, the day limit for sending update emails is #day_lmit, you had already sent #used update emails. From the available options, please choose a value 
        ///
        ///less than or equal to #available.
        ///
        ///.
        /// </summary>
        internal static string SelectedbusinessupdatelimitExceedstheAvailablevalue {
            get {
                return ResourceManager.GetString("SelectedbusinessupdatelimitExceedstheAvailablevalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your selected update limit value is less than or equal to the available limit value.Please schedule your update..
        /// </summary>
        internal static string SelectedBusinessUpdatelimitlessthanAvailablevalue {
            get {
                return ResourceManager.GetString("SelectedBusinessUpdatelimitlessthanAvailablevalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry, the day limit for sending coupons is #day_lmit, you had already sent #used coupons. From the available options, please choose a value less than or equal to #available..
        /// </summary>
        internal static string SelectedCouponlimitExceedstheAvailablevalue {
            get {
                return ResourceManager.GetString("SelectedCouponlimitExceedstheAvailablevalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your selected coupon limit value is less than or equal to the available limit value.Please schedule your coupon..
        /// </summary>
        internal static string SelectedCouponlimitlessthanAvailablevalue {
            get {
                return ResourceManager.GetString("SelectedCouponlimitlessthanAvailablevalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry, the day limit for sending emails is #day_lmit, you had already sent #used emails. From the available options, please choose a value less than or equal to #available..
        /// </summary>
        internal static string SelectedEmailslimitExceedstheAvailablevalue {
            get {
                return ResourceManager.GetString("SelectedEmailslimitExceedstheAvailablevalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry, the day limit for sending flyer is #day_lmit, you had already sent #used flyers. From the available options, please choose a value 
        ///
        ///less than or equal to #available.
        ///
        ///.
        /// </summary>
        internal static string SelectednewsletterlimitExceedstheAvailablevalue {
            get {
                return ResourceManager.GetString("SelectednewsletterlimitExceedstheAvailablevalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your selected flyer limit value is less than or equal to the available limit value.Please schedule your flyer..
        /// </summary>
        internal static string SelectednewsletterlimitlessthanAvailablevalue {
            get {
                return ResourceManager.GetString("SelectednewsletterlimitlessthanAvailablevalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have exceeded the maximum limit for today..
        /// </summary>
        internal static string sendaffiliatecountExceeded {
            get {
                return ResourceManager.GetString("sendaffiliatecountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have exceeded the maximum limit for today..
        /// </summary>
        internal static string sendBusinessEventcountExceeded {
            get {
                return ResourceManager.GetString("sendBusinessEventcountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your event has been scheduled successfully..
        /// </summary>
        internal static string sendBusinessEventmail {
            get {
                return ResourceManager.GetString("sendBusinessEventmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have exceeded the maximum limit for today..
        /// </summary>
        internal static string sendBusinessUpdatecountExceeded {
            get {
                return ResourceManager.GetString("sendBusinessUpdatecountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your update has been scheduled successfully..
        /// </summary>
        internal static string sendBusinessUpdatemail {
            get {
                return ResourceManager.GetString("sendBusinessUpdatemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have exceeded the maximum limit for today..
        /// </summary>
        internal static string sendcouponcountExceeded {
            get {
                return ResourceManager.GetString("sendcouponcountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your coupon has been sent successfully..
        /// </summary>
        internal static string sendcouponmail {
            get {
                return ResourceManager.GetString("sendcouponmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your content has been emailed successfully..
        /// </summary>
        internal static string SendEmailContacts {
            get {
                return ResourceManager.GetString("SendEmailContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have exceeded the maximum limit for today..
        /// </summary>
        internal static string sendEmailcountExceeded {
            get {
                return ResourceManager.GetString("sendEmailcountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have exceeded the maximum limit for today..
        /// </summary>
        internal static string sendgeneraltabcountExceeded {
            get {
                return ResourceManager.GetString("sendgeneraltabcountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email campaign has been sent successfully..
        /// </summary>
        internal static string SendMailfromMessageLabelMessage {
            get {
                return ResourceManager.GetString("SendMailfromMessageLabelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have exceeded the maximum limit for today..
        /// </summary>
        internal static string SendMessagecountExceeded {
            get {
                return ResourceManager.GetString("SendMessagecountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have exceeded the maximum limit for today..
        /// </summary>
        internal static string sendnewslettercountExceeded {
            get {
                return ResourceManager.GetString("sendnewslettercountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your campaign has been scheduled to be sent..
        /// </summary>
        internal static string sendnewslettermail {
            get {
                return ResourceManager.GetString("sendnewslettermail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your notification has been sent successfully to few devices only..
        /// </summary>
        internal static string SentPartialPushNotification {
            get {
                return ResourceManager.GetString("SentPartialPushNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your notification has been sent successfully..
        /// </summary>
        internal static string SentPushNotification {
            get {
                return ResourceManager.GetString("SentPushNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your short logo must be a minimum of.
        /// </summary>
        internal static string ShortlogoUploadMessage {
            get {
                return ResourceManager.GetString("ShortlogoUploadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access Categories.
        /// </summary>
        internal static string SmartConnectCategoryPermission {
            get {
                return ResourceManager.GetString("SmartConnectCategoryPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartConnect button created successfully.
        /// </summary>
        internal static string SmartConnectCreated {
            get {
                return ResourceManager.GetString("SmartConnectCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartConnect button has been deleted successfully.
        /// </summary>
        internal static string SmartConnectDeleted {
            get {
                return ResourceManager.GetString("SmartConnectDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to manage smartconnect messages..
        /// </summary>
        internal static string SmartConnectPermission {
            get {
                return ResourceManager.GetString("SmartConnectPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartConnect button details updated successfully.
        /// </summary>
        internal static string SmartConnectUpdated {
            get {
                return ResourceManager.GetString("SmartConnectUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have sufficient SMS credits to send now. Please buy more SMS credits..
        /// </summary>
        internal static string SMSAvailableExceeded {
            get {
                return ResourceManager.GetString("SMSAvailableExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected sponsor ad has been deleted successfully..
        /// </summary>
        internal static string SponsorAdDeleteSuccess {
            get {
                return ResourceManager.GetString("SponsorAdDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Display status has been updated for Sponsor ads..
        /// </summary>
        internal static string SponsorAdsAppdisplaySuccess {
            get {
                return ResourceManager.GetString("SponsorAdsAppdisplaySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponser Ad Status has been updated Sucessfully.
        /// </summary>
        internal static string SponsorAdsUpdateSuccess {
            get {
                return ResourceManager.GetString("SponsorAdsUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit sponsor Ad Link.
        /// </summary>
        internal static string SponsorBannerAdLinkEdit {
            get {
                return ResourceManager.GetString("SponsorBannerAdLinkEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link has been updated for sponsor ad..
        /// </summary>
        internal static string SponsorBannerAdLinkSaved {
            get {
                return ResourceManager.GetString("SponsorBannerAdLinkSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your image has been uploaded successfully..
        /// </summary>
        internal static string SponsorBGImageSubmitted {
            get {
                return ResourceManager.GetString("SponsorBGImageSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your invitation have been sent successfully..
        /// </summary>
        internal static string SubAppInvitationRequest {
            get {
                return ResourceManager.GetString("SubAppInvitationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have created #ResultCount#. Please try again for remaining codes..
        /// </summary>
        internal static string SubAppReqCodesFailed {
            get {
                return ResourceManager.GetString("SubAppReqCodesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will contact you soon to activate the requested #Count# code(s) for Pre-Paid..
        /// </summary>
        internal static string SubAppReqCodesPaidSuccess {
            get {
                return ResourceManager.GetString("SubAppReqCodesPaidSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested #Count# code(s) for Unpaid have been generated successfully..
        /// </summary>
        internal static string SubAppReqCodesUnPaidSuccess {
            get {
                return ResourceManager.GetString("SubAppReqCodesUnPaidSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a text to find affiliate(s)..
        /// </summary>
        internal static string SubappsEmptySearch {
            get {
                return ResourceManager.GetString("SubappsEmptySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation has not send. Please try again..
        /// </summary>
        internal static string SubInvitationFailed {
            get {
                return ResourceManager.GetString("SubInvitationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation has been sent successfully..
        /// </summary>
        internal static string SubInvitationSuccess {
            get {
                return ResourceManager.GetString("SubInvitationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected sender(s) have been unblocked successfully..
        /// </summary>
        internal static string UnblockedAllSenders {
            get {
                return ResourceManager.GetString("UnblockedAllSenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sender have been unblocked successfully.
        /// </summary>
        internal static string UnblockSender {
            get {
                return ResourceManager.GetString("UnblockSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email has already been unsubscribed from this list..
        /// </summary>
        internal static string UnsubscribeNotListed {
            get {
                return ResourceManager.GetString("UnsubscribeNotListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been successfully removed from this subscriber list..
        /// </summary>
        internal static string UnsubscribeSucess {
            get {
                return ResourceManager.GetString("UnsubscribeSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your USPDhub shortcut to desktop with username has been created successfully..
        /// </summary>
        internal static string URLshortcutUsername {
            get {
                return ResourceManager.GetString("URLshortcutUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your USPDhub shortcut to desktop with username and password has been created successfully..
        /// </summary>
        internal static string URLshortcutUserPwd {
            get {
                return ResourceManager.GetString("URLshortcutUserPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message has been sent successfully..
        /// </summary>
        internal static string VMSuccess {
            get {
                return ResourceManager.GetString("VMSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already been registered..
        /// </summary>
        internal static string WebnairAlreadyRegistered {
            get {
                return ResourceManager.GetString("WebnairAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has been occured. Please try again after some time..
        /// </summary>
        internal static string WebnairError {
            get {
                return ResourceManager.GetString("WebnairError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for registering..
        /// </summary>
        internal static string WebnairSuccess {
            get {
                return ResourceManager.GetString("WebnairSuccess", resourceCulture);
            }
        }
    }
}
